id: A7111227F
base_file: f446F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:09:53.789011
  last_modified_at: 2022-05-30 22:09:53.789016
