id: A7111227F
base_file: fC7E5.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:09:53.819079
  last_modified_at: 2022-05-30 22:09:53.819083
