id: A7111227F
base_file: f0AE4.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:09:53.771907
  last_modified_at: 2022-05-30 22:09:53.771911
