id: A7111227F
base_file: f2E4E.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:09:53.782695
  last_modified_at: 2022-05-30 22:09:53.782699
