id: A7111227F
base_file: fDEF1.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:09:53.823109
  last_modified_at: 2022-05-30 22:09:53.823112
