id: A7111227F
base_file: fCF4F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:09:53.820040
  last_modified_at: 2022-05-30 22:09:53.820043
